xset -dpms
xset s off
docker start adguardhome

# Disable bell
xset -b

# Enable zapping (C-A-<Bksp> kills X)
setxkbmap -option terminate:ctrl_alt_bksp

setxkbmap tr
xset r rate 161 61

# Enforce correct locales from the beginning
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_CTYPE=en_US.utf8
export LC_MONETARY=en_US.utf8
export LC_NUMERIC=en_US.utf8
export LC_TIME=en_US.UTF-8
export LC_TIME=en_US.utf8
export LANG=en_US.UTF-8
export QT_QPA_PLATFORMTHEME=qt5ct

exec dunst &
exec slstatus &
xautolock -time 5 -locker slock &
exec copyq &
#exec xcompmgr &
#xrandr --dpi 180
#xrandr --output eDP-1 --mode 1920x1080
xrandr --output eDP-1 --mode 1600x900
feh --bg-scale .config/wall.png
wmname LG3D
#xgamma -gamma 0.8
#exec dwm
exec i3
